<?php

namespace Database\Seeders;

use App\Models\ProdukUmkm;
use Illuminate\Database\Seeder;

class ProdukUmkmSeeder extends Seeder
{
    public function run(): void
    {
        $umkm = [
            [
                'nama_produk' => 'Warung Alfaila',
                'nama_pemilik' => 'Fina',
                'jenis_usaha' => 'Binte dan Pop Ice',
                'alamat' => 'Dusun 1',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085342504300',
                'nama_kontak' => 'Fina',
                'jam_operasional' => '11 - 22',
                'produk_jasa' => 'Binte dan Pop Ice',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Kios Arul',
                'nama_pemilik' => 'Nur Ita',
                'jenis_usaha' => 'Jualan Sembako & Voucher Internet',
                'alamat' => 'RT 7 Dusun 4',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '082259494859',
                'nama_kontak' => 'Ibu Risa',
                'jam_operasional' => '6.30 - 22',
                'produk_jasa' => 'Sembako dan Voucher Internet',
                'lokasi_maps' => 'https://maps.app.goo.gl/bdEhJqaXLe5dwcVY8',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Mbak Sri',
                'nama_pemilik' => 'Ibu Srirahayu',
                'jenis_usaha' => 'Mie Kuah',
                'alamat' => 'RT 6 Dusun 3',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085687325054',
                'nama_kontak' => 'Ibu Srirahayu',
                'jam_operasional' => '11 - 17.30',
                'produk_jasa' => 'Mie Kuah, Pop Ice',
                'lokasi_maps' => 'https://maps.app.goo.gl/f67euLbvzUaBGQqG8',
                'keterangan_tambahan' => 'Menjual Pop Ice',
            ],
            [
                'nama_produk' => 'Warung Mama Nizam',
                'nama_pemilik' => 'Ibu Yulfianti',
                'jenis_usaha' => 'Pop Ice & Binte',
                'alamat' => 'RT 5 Dusun 3',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085757133803',
                'nama_kontak' => 'Ibu Yulfianti',
                'jam_operasional' => '11 - 17',
                'produk_jasa' => 'Pop Ice dan Binte',
                'lokasi_maps' => 'https://maps.app.goo.gl/UVmw9ph3KcCu1czz5',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Gorengan Mama Faruq',
                'nama_pemilik' => 'Anggun Saputi',
                'jenis_usaha' => 'Gorengan',
                'alamat' => 'RT 5 Dusun 3',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085845655377',
                'nama_kontak' => 'Anggun Saputi',
                'jam_operasional' => '12 - 18',
                'produk_jasa' => 'Aneka Gorengan',
                'lokasi_maps' => 'https://maps.app.goo.gl/z9Fvjyx4tdftRFSMA',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Cendol Ibu Huzaema',
                'nama_pemilik' => 'Ibu Huzaema',
                'jenis_usaha' => 'Es Cendol',
                'alamat' => 'RT 3 Dusun 2',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085825405069',
                'nama_kontak' => 'Ibu Huzaema',
                'jam_operasional' => '14 - 17.30',
                'produk_jasa' => 'Es Cendol',
                'lokasi_maps' => 'https://maps.app.goo.gl/W6QYAsVGwceuRqdU8',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Bu Nidar',
                'nama_pemilik' => 'Ibu Nidar',
                'jenis_usaha' => 'Mie Kuah',
                'alamat' => 'RT 2 Dusun 2',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => null,
                'nama_kontak' => 'Ibu Nidar',
                'jam_operasional' => '10 - 22',
                'produk_jasa' => 'Mie Kuah, Keripik Pisang, Rempeyek',
                'lokasi_maps' => 'https://maps.app.goo.gl/i6jcwXgcoMfGrGW47',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Attan',
                'nama_pemilik' => 'Ibu Desi Lasompoh',
                'jenis_usaha' => 'Warung Mas Joko',
                'alamat' => 'RT 2 Dusun 2',
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085342192370',
                'nama_kontak' => 'Ibu Desi Lasompoh',
                'jam_operasional' => '12 - 23',
                'produk_jasa' => null,
                'lokasi_maps' => 'https://maps.app.goo.gl/JU78jXy7W54T4mAK6',
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Sayur Ibu Warni',
                'nama_pemilik' => 'Ibu Warni',
                'jenis_usaha' => 'Sayur-sayuran',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085845891629',
                'nama_kontak' => 'Ibu Warni',
                'jam_operasional' => '7.30',
                'produk_jasa' => 'Sayur-sayuran',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Ibu Fika',
                'nama_pemilik' => 'Ibu Fika',
                'jenis_usaha' => 'Sayur, Mie, Binte',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '089502680861',
                'nama_kontak' => 'Ibu Fika',
                'jam_operasional' => '7 - 22',
                'produk_jasa' => 'Sayur, Mie, Binte',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Ibu Hartati',
                'nama_pemilik' => 'Ibu Hartati',
                'jenis_usaha' => 'Binte & Barang Campuran',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085752095109',
                'nama_kontak' => 'Ibu Hartati',
                'jam_operasional' => '7 - 22',
                'produk_jasa' => 'Binte dan Barang Campuran',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Ibu Satriani',
                'nama_pemilik' => 'Ibu Satriani',
                'jenis_usaha' => 'Nasi Kuning',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085823570385',
                'nama_kontak' => 'Ibu Satriani',
                'jam_operasional' => '6.30 - 10',
                'produk_jasa' => 'Nasi Kuning',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Nasi Kuning Nirmala',
                'nama_pemilik' => 'Nirmala',
                'jenis_usaha' => 'Nasi Kuning dan Kue',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085756304042',
                'nama_kontak' => 'Nirmala',
                'jam_operasional' => '7 - 10',
                'produk_jasa' => 'Nasi Kuning dan Kue',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
            [
                'nama_produk' => 'Warung Aniza',
                'nama_pemilik' => 'Aniza',
                'jenis_usaha' => 'Pisang Goreng, Es Campur, Pop Ice',
                'alamat' => null,
                'deskripsi' => null,
                'harga' => 0,
                'foto_path' => null,
                'no_whatsapp' => '085824609003',
                'nama_kontak' => 'Aniza',
                'jam_operasional' => 'Jumat-Minggu 13 - 21, Senin-Kamis 16 - 21',
                'produk_jasa' => 'Pisang Goreng, Es Campur, Pop Ice',
                'lokasi_maps' => null,
                'keterangan_tambahan' => null,
            ],
        ];

        ProdukUmkm::insert($umkm);
    }
}